project:
  type: website

website:
  title: "Visual Analytics"
  navbar: 
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_exercise/Hands-on_EX01/Hands-on_EX01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_exercise/Hands-on_EX02/Hands-on_EX02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_exercise/Hands-on_EX03/Hands-on_EX03.html"
      - text: "In-Class Exercise"
        menu: 
          - text: "In-Class Exercise 3"
            href: "In-class_Exercise/In-class_Ex03.html"
      - text: "Take Home Exercise"
        menu: 
          - text: "Take Home Exercise 1"
            href: "Take_Home_Exercise/Take_Home_Exercise_1/Take_Home_Exercise_1.html"
          - text: "Take Home Exercise 2"
            href: "Take_Home_Exercise/Take_Home_Exercise_2/Take_Home_Exercise_2.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual


